name: Auto-Merge mirror to hosted

on:
  # Triggers the workflow on push or pull request events but only for the "hosted" branch
  push:
    branches: [ "mirror" ]
  pull_request:
    branches: [ "hosted" ]
    types:
      - closed
  workflow_dispatch:

jobs:
  if_changes:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Merge mirror into hosted
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "mirror"
          git status
          git checkout "hosted"
          git merge "mirror" --no-edit
          git push
          git status
